package cs.youtrade.autotrade.client.telegram.menu;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
@AllArgsConstructor
public enum UserMenu {
    // reserved (menuId = 0)
    NONE(0),

    // main menu
    MAIN(1),
    MAIN_PARAMETERS_LIST(1),
    MAIN_PARAMETERS_SWITCH_STAGE_1(1),
    MAIN_PARAMETERS_SWITCH_STAGE_P(1),
    MAIN_PARAMETERS_CREATE_STAGE_1(1),
    MAIN_PARAMETERS_CREATE_STAGE_2(1),
    MAIN_PARAMETERS_CREATE_STAGE_P(1),
    MAIN_PARAMETERS_DELETE_STAGE_1(1),
    MAIN_PARAMETERS_DELETE_STAGE_P(1),
    MAIN_GET_NEWEST_ITEMS_STAGE_1(1),
    MAIN_GET_NEWEST_ITEMS_STAGE_P(1),

    PARAMS(2),
    PARAMS_RENAME(2),

    FOLLOW(9),
    FOLLOW_COPY(9),
    FOLLOW_FOLLOW(9),
    FOLLOW_UNFOLLOW(9),

    TOKENS(3),
    TOKENS_GET(3),
    TOKENS_ADD_BUY(3),
    TOKENS_ADD_SELL(3),
    TOKENS_REMOVE(3),

    AUTOBUY(4),
    AUTOBUY_UPDATE_FIELD_STAGE_1(4),
    AUTOBUY_UPDATE_FIELD_STAGE_2(4),
    AUTOBUY_UPDATE_FIELD_STAGE_P(4),
    AUTOBUY_SWITCH_FUNCTION_TYPE(4),
    AUTOBUY_SWITCH_DUPLICATE_MODE(4),
    AUTOBUY_TOGGLE_AUTOBUY(4),

    SCORING(5),
    SCORING_ADD_STAGE_1(5),
    SCORING_ADD_STAGE_2(5),
    SCORING_ADD_STAGE_P(5),
    SCORING_EDIT_STAGE_1(5),
    SCORING_EDIT_STAGE_2(5),
    SCORING_EDIT_STAGE_3(5),
    SCORING_EDIT_STAGE_P(5),
    SCORING_REMOVE_STAGE_1(5),
    SCORING_REMOVE_STAGE_P(5),

    WORDS(6),
    WORDS_ADD_STAGE_CHOOSE(6),
    WORDS_ADD_STAGE_1(6),
    WORDS_ADD_STAGE_P(6),
    WORDS_GET_STAGE_CHOOSE(6),
    WORDS_GET_STAGE_P(6),
    WORDS_REMOVE_STAGE_CHOOSE(6),
    WORDS_REMOVE_STAGE_1(6),
    WORDS_REMOVE_STAGE_P(6),
    WORDS_REMOVE_ALL_STAGE_CHOOSE(6),
    WORDS_REMOVE_ALL_STAGE_P(6),

    AUTOSELL(7),
    AUTOSELL_UPDATE_FIELD_STAGE_1(7),
    AUTOSELL_UPDATE_FIELD_STAGE_2(7),
    AUTOSELL_UPDATE_FIELD_STAGE_P(7),
    AUTOSELL_SWITCH_EVAL_MODE(7),
    AUTOSELL_SWITCH_EVAL_MODE_S1(7),
    AUTOSELL_TOGGLE_AUTOSELL(7),

    TABLE(8),
    TABLE_SELLING_STAGE_1(8),
    TABLE_SELLING_STAGE_P(8),
    TABLE_WAITING(8),
    TABLE_HISTORY_STAGE_1(8),
    TABLE_HISTORY_STAGE_P(8),
    TABLE_UPLOAD_STAGE_1(8),
    TABLE_UPLOAD_STAGE_P(8),
    TABLE_CHANGE_STAGE_CHOOSE(8),
    TABLE_CHANGE_STAGE_1(8),
    TABLE_CHANGE_STAGE_P(8),
    TABLE_RESTRICT_STAGE_1(8),
    TABLE_RESTRICT_STAGE_P(8);

    private final int menuId;
}
